dist: xenial
language: python
matrix:
    include:
        - python: 3.6
        - python: 3.7
branches:
  only:
    - master
install:
  - python setup.py install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - python setup.py test
after_success:
  - ./cc-test-reporter after-build --debug --coverage-input-type=coverage.py --exit-code $TRAVIS_TEST_RESULT; fi
  - mkdir docs
  - export PYTHONPATH=`pwd`
  - pip install recommonmark sphinx sphinxcontrib-napoleon travis-sphinx
  - sphinx-quickstart -q -p scikit-sacred -a "David Diaz Vico" -v 0.1 -r 0.1.2 -l en --ext-autodoc --ext-viewcode --ext-githubpages --extensions sphinxcontrib.napoleon --no-makefile --no-batchfile docs
  - sphinx-apidoc -o docs/_static/ sksacred -F -a -l
  - travis-sphinx -v build -s docs -n
  - travis-sphinx deploy